### PR TITLE
Added state symbols to GUI for bone normalize

### PR DESCRIPTION
**Pull request by sts1skj**
I added two new icons, icoChange and icoNone, which represent whether or
not a bone is to be included in normalization.  I added these to the GUI
in the bones tab and made them work.

This also required many changes to the normalization code in TweakBrush.

### CODE REVIEW

**Comment by ousnius** [comment]
@sts1skj Works pretty well thanks, however I got a crash when I selected two meshes at once, made the three spine bones the normalized/balanced bones and painted on it.

Did you make sure all the changes work with having more than one mesh for painting selected at once? I used the "Bowsette Corset" for CBBE SE.

**Comment by ousnius** [comment]
@sts1skj Works pretty well thanks, however I got a crash when I selected a specific mesh, made the three spine bones the normalized/balanced bones and painted on it. I used the "Bowsette Corset" for CBBE SE.

**Comment by ousnius** [comment]
lWPtrs has null entries.

image

**Comment by sts1skj** [comment]
Commit 91cb774 should fix that.

**Comment by sts1skj** [comment]
It still doesn't work right.  I'm working on it.

**Comment by sts1skj** [comment]
Hopefully it works correctly now.

**Comment by ousnius** [comment]
Seems fine now. 👍

**Pull request merged**
